### ISSUE TITLE
UI/UX signoff of the login to external website on desktop epic

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#150]
Acceptance criteria

- [ ] UX designer reviews the epic and tries the functional acceptance criteria on staging app
- [ ] any design discrepancies are documented in a new Github issue(s)
- [ ] remove the design changes from the design changelog

design changelog https://docs.google.com/spreadsheets/d/1Pr2yxJrdkBvcPUoh9IGMmgeRNXPipm64BkAigovCtBM/edit#gid=0
testing procedure https://www.notion.so/tonomy-foundation/Tonomy-ID-Testing-Procedure-4a084f9e43df413695425289ca017446
