### ISSUE TITLE
Epics / roadmap - business case review

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID-Management#41]
Definition of done:

- [ ] Current TIPs are converted to user story style
- [ ] Current non-actiive epics in Tonomy ID board are moved to TIPs
- [ ] Epics and roadmap are reviewed and re-prioritised based on business case

Follow up

-  visual representation of the roadmap
